### ISSUE TITLE
`NestedRoutes` not working with `erase-components` feature

### ISSUE THREAD

**Issue by NCura** [leptos-rs/cargo-leptos#503]
The following code was working with `cargo-leptos 0.2.32`:

```rust
#[component]
pub fn App() -> impl IntoView {
    view! {
        <Router>
            <Routes fallback=|| "Not found.">
                <AppRoutes />
            </Routes>
        </Router>
    }
}

#[component(transparent)]
fn AppRoutes() -> impl MatchNestedRoutes + Clone {
    view! {
        <ParentRoute path=path!("") view=Outlet>
            <Route path=path!("") view=|| "Home" />
        </ParentRoute>

        <ParentRoute path=path!("") view=Outlet>
            <Route path=path!("other") view=|| "Home" />
        </ParentRoute>
    }
    .into_inner()
}
```

But since `cargo-leptos 0.2.33`, it produces the following error:

```rust
error[E0308]: mismatched types
  --> app/src/lib.rs:44:5
   |
42 |   #[component(transparent)]
   |   ------------------------- expected `AnyNestedRoute` because of return type
43 |   fn AppRoutes() -> impl MatchNestedRoutes + Clone {
44 | /     view! {
45 | |         <ParentRoute path=path!("") view=Outlet>
46 | |             <Route path=path!("") view=|| "Home" />
47 | |         </ParentRoute>
...  |
53 | |     .into_inner()
   | |_________________^ expected `AnyNestedRoute`, found `StaticVec<AnyNestedRoute>`
   |
   = note: expected struct `AnyNestedRoute`
              found struct `StaticVec<AnyNestedRoute>`
```

Adding `disable-erase-components = true` to `Cargo.toml` removes the error.
Is this a bug, or is there a better way to write the `AppRoutes` to conform to the new `erase-components` feature?
